#!/bin/bash
set -euo pipefail
root=$(git rev-parse --show-toplevel)
objects=()
while read -r _local_ref local_sha _remote_ref _remote_sha; do
  [ "$local_sha" != 0000000000000000000000000000000000000000 ] || continue
  objects+=("$local_sha")
done
exec "$root/bin/check" "${objects[@]}"
